### PR TITLE
Wip/add auth plugin

### PR DESCRIPTION
**Pull request by bewest**
Adds http and redis support for the auth plugin.

### CODE REVIEW

**Comment by jllopis** [comment]
Thanks for your PR. Nice to have this auth plugin in. Why move to Ubuntu? This is debian because it is what we use and we're now moving to Alpine Linux.
If you need Ubuntu and do not want to build libwebsockets I will cherry-pick the auth-plugin commits so you can continue with your branch.
What do you think?

**Comment by bewest** [comment]
Howdy!  Thanks for your consideration.

I felt about about changing your base image: the only reason was that I had a hard time fetching the libwebsocket sources (both from warmcat and github.  I knew ubuntu had it as a nice package and was feeling impatient.  My main goal was introducing the auth plug in and I'd be interested in returning to your base if you get it working.

**Comment by jllopis** [comment]
I got it. I'll try to push tonight with your changes (cherry-picked). The plugin gets installed and cut the image size almost in half.
I'm also trying to making more compliant with the docker library guidelines.

**Comment by bewest** [comment]
Actually FWIW, I chose yours because it used `RUN` so heavily, which seems to be the docker recommendation.

I split up the run tasks a bit and made use of `ENV` so that maintaining each large step would be faster/easier.  I noticed it definitely makes it faster to only re-do the steps that have failed.

Looking forward to the slimmer image.  Thanks again!

**Comment by jllopis** [comment]
Done! Cherry-picked the `auth-plugin` commits and got it working.
I also updated `README.md` and added sample *auth config*. If you use `docker-compose` there is also a `docker-compose.yml` there.

**Comment by bewest** [comment]
Very nice.  Thanks!
I see you managed to install libhiredis itself. :)

FWIW, I abandoned the the redis plugin for the http version.
It's incredibly simple to prop up another http service which does interesting things, here's another example: https://github.com/bewest/restify-mosquitto-auth

Nice thing about the http auth plugin is that the domain and other attributes can bet set based on environment variables.

**Comment by jllopis** [comment]
Looks cool. What I like from the redis backend is that there is one almost everywhere :) The bad thing is that mosquitto will break if the redis backend is not found or dissapear, and this isn't exactly nice. This will not happen with http backend.
I added some sample config for the http backend also. BTW, upgraded to debian jessie (saved 100MB).

**Pull request closed without merging**
